server:
  port: 8081
  servlet:
    context-path:

cloud:
  aws:
    accessKey: idDyk1eqeu4jbbL1AW5V
    secretKey: ISRq73JiZPVA5DFGFnFBsfBSS1in2du4vwuVgLxv
    endpoint: https://172.21.235.124:443


#accessKey: idDyk1eqeu4jbbL1AW5V
#    secretKey: ISRq73JiZPVA5DFGFnFBsfBSS1in2du4vwuVgLxv
#    endpoint: https://172.21.235.124:443


#    minio地址
#    accessKey: WJ8KSU22Z57W9NZ5BYZG
#    secretKey: +kSjNYuuNxLwB+JCF2oW+OSJJEnGrNivpsKZfjtb
#    endpoint: http://127.0.0.1:9000/

#    accessKey: *****
#    secretKey: *****
#    endpoint: http://s3.amazonaws.com